basePath: /v1
definitions:
  controller.LoginParams:
    properties:
      user_name:
        type: string
      user_password:
        type: string
    type: object
  modal.BookInfo:
    properties:
      author:
        type: string
      bookList:
        items:
          $ref: '#/definitions/modal.BookList'
        type: array
      bookName:
        type: string
      bookStock:
        type: integer
      context:
        type: string
      isbn:
        type: string
      pageNum:
        type: string
      photo:
        type: string
      price:
        type: number
      publishTime:
        type: string
      publisher:
        type: string
      translator:
        type: string
      typeId:
        type: integer
    type: object
  modal.BookList:
    properties:
      bookInfo:
        items:
          $ref: '#/definitions/modal.BookInfo'
        type: array
      id:
        type: integer
      name:
        type: string
      photo:
        type: string
      remake:
        type: string
      time:
        type: string
      user:
        items:
          $ref: '#/definitions/modal.User'
        type: array
      userId:
        type: integer
    type: object
  modal.BookType:
    properties:
      id:
        type: integer
      level:
        type: string
      pId:
        type: integer
      remake:
        type: string
      typeName:
        type: string
    type: object
  modal.BookTypeReqParams:
    properties:
      current:
        type: integer
      keyWord:
        type: string
      level:
        type: string
      order_by:
        type: string
      order_type:
        type: string
      pName:
        type: string
      pageSize:
        type: integer
      typeName:
        type: string
    type: object
  modal.QueryUserParams:
    properties:
      borrow_book_count:
        type: string
      current:
        type: integer
      order_by:
        type: string
      order_type:
        type: string
      pageSize:
        type: integer
      role:
        type: string
      user_name:
        type: string
    type: object
  modal.Result:
    properties:
      data: {}
    type: object
  modal.Role:
    properties:
      id:
        type: integer
      role_name:
        type: string
      role_weight:
        type: integer
    type: object
  modal.RoleListResult:
    properties:
      id:
        type: integer
      role_name:
        type: string
      role_weight:
        type: string
    type: object
  modal.RoleParams:
    properties:
      current:
        type: integer
      pageSize:
        type: integer
      role_name:
        type: string
    type: object
  modal.SelectOption:
    properties:
      label:
        type: string
      value:
        type: any
    type: object
  modal.TableResult:
    properties:
      data: {}
      total:
        type: integer
    type: object
  modal.TreeBookType:
    properties:
      children:
        items:
          $ref: '#/definitions/modal.TreeBookType'
        type: array
      id:
        type: integer
      level:
        type: string
      name:
        type: string
      pId:
        type: integer
      remake:
        type: string
    type: object
  modal.User:
    properties:
      birthday:
        type: string
      bookList:
        items:
          $ref: '#/definitions/modal.BookList'
        type: array
      borrow_book_count:
        type: integer
      email:
        type: string
      id:
        type: integer
      phone:
        type: string
      remake:
        type: string
      role:
        type: string
      sex:
        type: integer
      user_name:
        type: string
      user_password:
        type: string
    type: object
  modal.UserListResult:
    properties:
      birthday:
        type: string
      borrow_book_count:
        type: integer
      email:
        type: string
      id:
        type: integer
      phone:
        type: string
      remake:
        type: string
      role:
        type: string
      roleName:
        type: string
      sex:
        type: integer
      user_name:
        type: string
    type: object
host: petstore.swagger.io
info:
  contact: {}
  title: Swagger Example API
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 登陆
      parameters:
      - description: 登陆用户名和密码
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/controller.LoginParams'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.Result'
  /v1/bookType/add:
    post:
      consumes:
      - application/json
      description: "新增\U0001F4D6类型"
      parameters:
      - description: "新增\U0001F4D6的数据"
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/modal.BookType'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.Result'
  /v1/bookType/delete:
    delete:
      consumes:
      - application/json
      description: 删除图书分类
      parameters:
      - description: "删除图书分类的\U0001F194"
        in: body
        name: user
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.Result'
  /v1/bookType/list:
    post:
      consumes:
      - application/json
      description: 获取图书分类列表
      parameters:
      - description: 查询参数
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/modal.BookTypeReqParams'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.TableResult'
  /v1/bookType/treeList:
    get:
      consumes:
      - application/json
      description: 返回树形结构的图书类型
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/modal.TreeBookType'
            type: array
  /v1/bookType/update:
    post:
      consumes:
      - application/json
      description: 更新图书分类列表
      parameters:
      - description: 更新参数
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/modal.BookType'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.Result'
  /v1/role/add:
    post:
      consumes:
      - application/json
      description: 新增角色
      parameters:
      - description: 新增角色的数据
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/modal.Role'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.Result'
  /v1/role/delete:
    delete:
      consumes:
      - application/json
      description: 删除角色
      parameters:
      - description: 删除角色的id
        in: body
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.Result'
  /v1/role/list:
    post:
      consumes:
      - application/json
      description: 查询角色
      parameters:
      - description: 查询角色的信息
        in: body
        name: req
        schema:
          $ref: '#/definitions/modal.RoleParams'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.RoleListResult'
  /v1/role/option:
    get:
      consumes:
      - application/json
      description: 查询角色的下拉选项
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.SelectOption'
  /v1/role/update:
    post:
      consumes:
      - application/json
      description: 修改角色
      parameters:
      - description: 新增角色的数据
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/modal.Role'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.Result'
  /v1/user/add:
    post:
      consumes:
      - application/json
      description: 新增用户
      parameters:
      - description: 新增用户的数据
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/modal.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.Result'
  /v1/user/delete:
    delete:
      consumes:
      - application/json
      description: 删除用户
      parameters:
      - description: 删除用户
        in: body
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.Result'
  /v1/user/list:
    post:
      consumes:
      - application/json
      description: 查询用户
      parameters:
      - description: 查询用户的信息
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/modal.QueryUserParams'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.UserListResult'
  /v1/user/update:
    post:
      consumes:
      - application/json
      description: 修改用户
      parameters:
      - description: 修改用户的数据
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/modal.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modal.Result'
swagger: "2.0"
